# Generated by Django 6.0.6 on 2026-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentrequest',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
