# Generated by Django 6.0.6 on 2026-07-06 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_developmentrequest_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developmentrequest',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('WATER', 'Water Infrastructure & Supply'), ('ROAD', 'Road Damage & Public Transport'), ('HEALTH', 'Public Health & Medical Centers'), ('EDUCATION', 'Education, Literacy & Schools'), ('ELECTRICITY', 'Power Supply & Grid Management'), ('SANITATION', 'Public Sanitation & Cleanliness'), ('WASTE', 'Waste Management & Garbage Disposal'), ('SAFETY', 'Public Safety & Law Enforcement'), ('WOMEN_CHILD', 'Women & Child Development'), ('ENVIRONMENT', 'Environment, Parks & Pollution'), ('AGRICULTURE', 'Agriculture & Rural Development')], default='WATER', max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', '⏳ Pending'), ('IN_PROGRESS', '⚙️ In Progress'), ('RESOLVED', '✅ Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
